### ISSUE TITLE
Multiple-User Query

### ISSUE THREAD

**Issue by garylancelot** [KaartGroup/Changesets2CSV#1]
1. It would be awesome to have the ability to not only query my whole team at one time, but for it to create one file with separated sheets for each editor.

1. It would also be cool if it had the ability in the file it creates to create a cell each for total edits, total changesets, and total discussions that could be queried and entered into another sheet, such as in [this example](https://github.com/KaartGroup/Changesets2CSV/files/3086748/Clingstone.Stats.April.7th.2019.xlsx).

##### This script is *AWESOME* so far!!!

**Comment by zlavergne** [comment]
> 1. It would be awesome to have the ability to not only query my whole team at one time, but for it to create one file with separated sheets for each editor.

The way this will have to work is that the script will create multiple csv's but you should be able to pull each csv into an excel doc as separate sheets. I haven't tested that but that's how it should _theoretically_ work. 

> 2. It would also be cool if it had the ability in the file it creates to create a cell each for total edits, total changesets, and total discussions that could be queried and entered into another sheet, such as in [this example](https://github.com/KaartGroup/Changesets2CSV/files/3086748/Clingstone.Stats.April.7th.2019.xlsx).

This shouldn't be too difficult.

> ##### This script is _AWESOME_ so far!!!
🎉

**Comment by zlavergne** [comment]
closed with #3
